# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Pipeline test CI
# coloca na parte on o evento que vai fazer disparar o workflow (ação no repositório que ativa)
on:
  push:
    branches: [ "main" ]   #condições que entram na condição para disparar o workflow (só se for push na main)
  pull_request:
    branches: [ "main" ] #condições que entram na condição para disparar o workflow (só se for PR na main)
  schedule:
    - cron: '0 12 * * *'  # Isso vai rodar todo dia às 12:00 PM UTC (9:00 AM BRT)
  workflow_dispatch:  # Permite rodar manualmente
  
# No jobs antes do passo a passo se coloca a conf de maquina
jobs:
  build:
    runs-on: ubuntu-latest #maquina virtual que sera executado o workflow 
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
# Aqui são os passo a passo que tem dentro do Jobs - configurações do job 
    steps:
    - uses: actions/checkout@v4 #ter acesso ao git e conseguir navegar no projeto tranquilamente e clona na maquina virtual
    - name: Use Node.js ${{ matrix.node-version }} 
      uses: actions/setup-node@v4 # setup do node (instalação) 
      with:
        node-version: ${{ matrix.node-version }} #versao que sera usada
    - run: npm install
    
    # Criação da pasta de relatório
    - name: Create report folder
      run: mkdir -p ./cypress/reports/mochawesome
    - name: Run Cypress tests
      run: npx cypress run

       # Arquivando os relatórios gerados
    - name: Armazenando relatório Mochawesome reports
      uses: actions/upload-artifact@v3
      with:
        name: mochawesome-report
        path: ./cypress/reports/mochawesome
