# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Pipeline test CI
# Essa parte são push e pull que apontam para branch main, vai rodar também quando mexer na main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 12 * * *'  # Isso vai rodar todo dia às 12:00 PM UTC (9:00 AM BRT)
  workflow_dispatch:  # Permite rodar manualmente
  
# Essa build está rodando em uma máquina ubuntu
# Em node-version coloca a maquina com alguma dessas versões, como tem uma matriz ele roda 3x
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
# Aqui temos os steps 
    steps:
    #configurações do job 
    - uses: actions/checkout@v4 #ter acesso ao git e conseguir navegar no projeto tranquilamente
    - name: Use Node.js ${{ matrix.node-version }} #aqui usa versão do node js, pega lá em node-version
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }} #usa setup do Node
    - run: npm install
    
    # Criação da pasta de relatório
    - name: Create report folder
      run: mkdir -p ./cypress/reports/mochawesome
    - name: Run Cypress tests
      run: npx cypress run

       # Arquivando os relatórios gerados
    - name: Upload Mochawesome reports
      uses: actions/upload-artifact@v3
      with:
        name: mochawesome-report
        path: ./cypress/reports/mochawesome
